### ISSUE TITLE
Courses at college campuses not showing up when waterloo campus is selected

### ISSUE THREAD

**Issue by karlwithak** [schybo/qu#5]
Steps to reproduce:

- Do search with default values, term: winter 2017, subject RS
- Only 1 course found
- Do related search here: http://www.adm.uwaterloo.ca/infocour/CIR/SA/under.html
- Lots of courses at STJ

Expected behavior:
All courses at STJ and CGC are shown when searching in waterloo campus
Or allow selecting college campuses specifically, and indicate that waterloo campus means waterloo minus college campuses

**Comment by schybo** [comment]
PR has fixed this issue. Expected behaviour is that all college campuses `var collegeCampuses = ['STJ J', 'CGC G', 'STP P', 'REN R'];` are now included when the campus is `UW U`.

Great find dude! 👏
