### ISSUE TITLE
Cannot click to remove courses when overlapping time slots

### ISSUE THREAD

**Issue by WBradbeer** [schybo/qu#6]
![image](https://cloud.githubusercontent.com/assets/8690237/20404732/31a5388c-acd4-11e6-9722-3e35e28ff9c6.png)

**Comment by schybo** [comment]
You also shouldn't be able to add the same course twice. That's stupid....

I'll fix that too hopefully

**Comment by schybo** [comment]
I fixed this issue in the quick CSS fix above. Making sure the course isn't already added is a lot more work and I'm going to break it out into it's own separate issue.
